'use strict';


export const FETCH_JOB_BY_ID_REQUEST = 'FETCH_JOB_BY_ID_REQUESTS';
export const FETCH_JOB_BY_ID_SUCCESS = 'FETCH_JOB_BY_ID_SUCCESS';
export const FETCH_JOB_BY_ID_FAILURE = 'FETCH_JOB_BY_ID_FAILURE';
export const FETCH_JOB_BY_ID = [ 
  FETCH_JOB_BY_ID_REQUEST,
  FETCH_JOB_BY_ID_SUCCESS,
  FETCH_JOB_BY_ID_FAILURE 
];

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUESTS';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE';
export const FETCH_JOBS = [ 
  FETCH_JOBS_REQUEST,
  FETCH_JOBS_SUCCESS,
  FETCH_JOBS_FAILURE 
];

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUESTS';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATE_JOB_FAILURE = 'CREATE_JOB_FAILURE';
export const CREATE_JOB = [ 
  CREATE_JOB_REQUEST,
  CREATE_JOB_SUCCESS,
  CREATE_JOB_FAILURE 
];

export const REMOVE_JOB_REQUEST = 'REMOVE_JOB_REQUESTS';
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS';
export const REMOVE_JOB_FAILURE = 'REMOVE_JOB_FAILURE';
export const REMOVE_JOB = [ 
  REMOVE_JOB_REQUEST,
  REMOVE_JOB_SUCCESS,
  REMOVE_JOB_FAILURE 
];

export const LOCK_QUEUE_REQUEST = 'LOCK_QUEUE_REQUESTS';
export const LOCK_QUEUE_SUCCESS = 'LOCK_QUEUE_SUCCESS';
export const LOCK_QUEUE_FAILURE = 'LOCK_QUEUE_FAILURE';
export const LOCK_QUEUE = [ 
  LOCK_QUEUE_REQUEST,
  LOCK_QUEUE_SUCCESS,
  LOCK_QUEUE_FAILURE 
];

export const RERUN_JOB_REQUEST = 'RERUN_JOB_REQUEST';
export const RERUN_JOB_SUCCESS = 'RERUN_JOB_SUCCESS';
export const RERUN_JOB_FAILURE = 'RERUN_JOB_FAILURE';
export const RERUN_JOB = [
  RERUN_JOB_REQUEST,
  RERUN_JOB_SUCCESS,
  RERUN_JOB_FAILURE,
]

export const SET_SELECTED_JOBS = 'SET_SELECTED_JOBS';